Testimonials
VPresich/team24-project-ukr pull request #10
Opened 2023-10-01 14:45 UTC by ndenchik

section testimonials

2023-10-01 17:49 UTC, VPresich requested changes

2023-10-01 17:49 UTC, VPresich commented on src/css/common.css
назви файлів малими буквами. В main вже є маленькі картинки потрібно додати ті, яких немає, чи видалити ті. Тому що ми не зможемо злити разом

2023-10-01 17:49 UTC, VPresich commented on src/css/testimonials.css
> +  .reviews-list-item{
.reviews-list-item:not(:first-child) {
  display: none;
} - приховати усі, окрім першого

 .reviews-list-item:nth-child(2) {
    display: inline-block;
  } - показати другий

2023-10-01 17:49 UTC, VPresich commented on src/css/testimonials.css
>  .container {
Це також видалити - перенесено в глобальні стилі

2023-10-01 17:51 UTC, VPresich commented
Конфлікт з main - буде непросто злити. Може із-за картинок

2023-10-01 18:41 UTC, ndenchik commented on src/css/common.css
OK

2023-10-01 18:45 UTC, ndenchik commented on src/css/testimonials.css
> +  .reviews-list-item{
ok

2023-10-01 18:46 UTC, ndenchik commented on src/css/testimonials.css
>  .container {
OK

2023-10-02 10:45 UTC, VPresich requested changes

2023-10-02 10:45 UTC, VPresich commented on src/img/reviews/Maria_Tkachuk.jpg
Назва файлів МАЛЕНЬКИМИ БУКВАМИ

2023-10-02 10:46 UTC, VPresich commented
Всі файли назви МАЛЕНЬКИМИ БУКВАМИ через тире

2023-10-02 18:36 UTC, ndenchik commented
дякую, вже було МАЛЕНЬКИМИ БУКВАМИ, не розумію, чому не показав...

2023-10-02 20:21 UTC, VPresich requested changes

2023-10-02 20:21 UTC, VPresich commented on src/img/reviews/Maria_Tkachuk@2x.jpg
Маленькими літерами

2023-10-02 20:22 UTC, VPresich commented
Я добавлю картинки сама (тому що це вже занадто)

2023-10-02 20:29 UTC, ndenchik commented
для мене теж вже занадто...

2023-10-02 20:32 UTC, ndenchik commented
знайшла помилку

2023-10-02 20:33 UTC, ndenchik commented
не треба добавляти, це моя робота і це я повинна навчитися, дякую

2023-10-02 20:43 UTC, VPresich commented
На вас назначений пулреквест - давайте навчимося робити ревью

2023-10-02 20:44 UTC, VPresich commented
Після успішного додавання картинок - виправите в коді й ще раз закомітите

2023-10-02 20:49 UTC, VPresich commented
Common.css  не комітити

2023-10-02 20:50 UTC, VPresich commented
Це не тільки ВАЩА робота - це робота команди

2023-10-02 20:55 UTC, VPresich commented
Перед тим як комітити потрібно брати нову версію з сервера

2023-10-02 20:58 UTC, VPresich commented
https://github.com/VPresich/team24-project-ukr/pull/15 тут Ваші картинки - давайте вже хоча б їх додамо за два дні

2023-10-02 21:04 UTC, VPresich approved these changes

2023-10-02 21:04 UTC, merged