Footer
VPresich/team24-project-ukr pull request #13
Opened 2023-10-02 16:45 UTC by Just1Anya

2023-10-02 20:00 UTC, VPresich requested changes

2023-10-02 20:00 UTC, VPresich commented on src/img/img_footer/retina/elements-desktop-1280@1x.png
Вже добавлені такі картинки

2023-10-02 20:00 UTC, VPresich commented
![Screenshot 2023-10-02 at 21 57 06](https://github.com/VPresich/team24-project-ukr/assets/111353667/c4b7a067-f12e-402e-be81-b0f303ac0cba)

2023-10-03 16:04 UTC, Just1Anya commented
Вибачаюсь, не перевіряла пошту.Med vänlig hälsning/ AnnaOn 02/10/2023, 22:00 Valentyna Aleksandrova ***@***.***> wrote:

   
  @VPresich requested changes on this pull request. 
   
  On ***@***.***: 
  Вже добавлені такі картинки 
  —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-10-05 00:01 UTC, VPresich commented
Зафікшено, внесено в main

2023-10-05 00:01 UTC, closed without merging