Your order last
VPresich/team24-project-ukr pull request #9
Opened 2023-10-01 14:06 UTC by genbaku

замінив всі letter-spacing: з пікселів на em 
додав потрібний відступ, всі інші начебто в нормі
вибачте що так довго, немає вільного часу...

2023-10-01 16:23 UTC, VPresich requested changes

2023-10-01 16:23 UTC, VPresich commented on src/css/order.css
>    .section-title {
Цей клас в common.cs

2023-10-01 16:31 UTC, VPresich commented
Не побачила, де ви змінили відстань між картинкою та формою.  Ще з'явилася проблема з картинкою в бекграунді. Треба щось придумати, щоб не ламався контейнер сторінки - може прив'язати до контейнера, а не до сторінки. У загальній вітці закоментований виклик секцій, де використовується бекграунд. Для нормальної роботи розкоментуйте тільки свою секцію (файл  styles.css)

2023-10-01 23:32 UTC, genbaku commented on src/css/order.css
> +  .order-img-container{
це відстань від зображення до форми

2023-10-02 20:17 UTC, VPresich approved these changes

2023-10-02 20:18 UTC, merged